// <auto-generated />
namespace MyBookingRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Check_up : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Check_up));
        
        string IMigrationMetadata.Id
        {
            get { return "202011131951103_Check_up"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
